name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  source-directory:
    description: 'Source directory from the origin directory'
    required: true
  destination-github-username:
    description: 'Name of the destination username/organization'
    required: true
  destination-repository-name:
    description: 'Destination repository'
    required: true
  user-email:
    description: 'Email for the git commit'
    required: true
  dst-branch:
    description: 'Destination branch'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-directory }}
    - ${{ inputs.destination-github-username }}
    - ${{ inputs.destination-repository-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.dst-branch }}
branding:
  icon: 'git-commit'
  color: 'green'
